module.exports = {
  time: '',
  lapTime: '',
  lapDistance: '',
  totalDistance: '',
  x: '',
  y: '',
  z: '',
  speed: '',
  xv: '',
  yv: '',
  zv: '',
  xr: '',
  yr: '',
  zr: '',
  xd: '',
  yd: '',
  zd: '',
  susp_pos_bl: '',
  susp_pos_br: '',
  susp_pos_fl: '',
  susp_pos_fr: '',
  susp_vel_bl: '',
  susp_vel_br: '',
  susp_vel_fl: '',
  susp_vel_fr: '',
  wheel_speed_bl: '',
  wheel_speed_br: '',
  wheel_speed_fl: '',
  wheel_speed_fr: '',
  throttle: '',
  steer: '',
  brake: '',
  clutch: '',
  gear: '',
  gforce_lat: '',
  gforce_lon: '',
  lap: '',
  engineRate: '',
  sli_pro_native_support: '',
  car_position: '',
  kers_level: '',
  kers_max_level: '',
  drs: '',
  traction_control: '',
  anti_lock_brakes: '',
  fuel_in_tank: '',
  fuel_capacity: '',
  in_pits: '',
  sector: '',
  sector1_time: '',
  sector2_time: '',
  brakes_temp1: '', // 4
  brakes_temp2: '', // 4
  brakes_temp3: '', // 4
  brakes_temp4: '', // 4
  wheels_pressure1: '', // 4
  wheels_pressure2: '', // 4
  wheels_pressure3: '', // 4
  wheels_pressure4: '', // 4
  team_info: '',
  total_laps: '',
  track_size: '',
  last_lap_time: '',
  max_rpm: '',
  idle_rpm: '',
  max_gears: '',
  sessionType: '',
  drsAllowed: '',
  track_number: '',
  vehicleFIAFlags: '',
};
